### ISSUE TITLE
Support multiple solutions

### ISSUE THREAD

**Issue by plutov** [plutov/practice-go#44]
Often we have >1 good solutions, I want to keep them all in the repo and don't lose. So we need a way to submit all possible working solutions.

**Comment by shogg** [comment]
A lightweight approach:
* a script (re-)generates the README.md in problem folders
* the README.md explains the problem as it does now
* after that follows a table with solutions
* the table has links to commits of benchmarked solutions in other repositories
    * if not github, ignore in the first step
    * urls to other github-repositories should be derivable
* the merged winner solution is marked in some way (on top)

Pros:
* all procedures stay the same
* README.md lists results

Cons:
* continuous regeneration of benchmark results in README.md might be too difficult/dangerous
    * benchmark new solutions and add results manually

**Comment by plutov** [comment]
Like this,
@shogg can you select 1 task and provide a possible solution for this specific task? I want to see how it may look like.
And agree, in this repo we can merge selected solution, but have links to PRs.
