### ISSUE TITLE
nodedegree: minor simplifications

### ISSUE THREAD

**Issue by shogg** [plutov/practice-go#59]
Hi plutov,
I'm glad you're back with a new challenge.

I want to suggest a minor change:

change:
`var smallGraph = [][]int{
	[]int{1, 2},
	[]int{1, 3},
}`

to:
`var smallGraph = [][2]int{
	{1, 2},
	{1, 3},
}`

This makes smallGraph a slice of values (slice elements are pointers in disguise). It assures the values to be fixed arrays with exactly two elements. And the whole data structure is densely packed.

I didn't start the challenge yet but I presume it will be more efficient to juggle with two element arrays instead of arbitrary size slices.

**Comment by plutov** [comment]
Totally agree, and the tests can remain the same I assume.

**Comment by plutov** [comment]
@shogg but how would you then change the function `Degree()` since it accepts slice with arbitrary size?

**Comment by shogg** [comment]
My suggestion is to change all occurrences of `[][]int` to `[][2]int`. If desired I can send a PR later this evening.

**Comment by plutov** [comment]
Ah, true, each pair has 2 items only. I will change it, no worries.
